<a href="https://colab.research.google.com/github/SHEU6000/TECH-BRO/blob/master/Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('STEG_BILLING_HISTORY.csv')

In [ ]:
client_0_bills = df.head(10)
client_0_bills

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,3/24/2014,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,3/29/2013,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,3/23/2015,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,7/13/2015,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,11/17/2016,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC
5,train_Client_0,7/17/2017,11,1335667.0,0,207,9.0,1,314,0,0,0,15638,15952,8,ELEC
6,train_Client_0,12/7/2018,11,1335667.0,0,207,9.0,1,541,0,0,0,15952,16493,12,ELEC
7,train_Client_0,3/19/2019,11,1335667.0,0,207,9.0,1,585,0,0,0,16493,17078,8,ELEC
8,train_Client_0,7/22/2011,11,1335667.0,0,203,9.0,1,1200,186,0,0,7770,9156,4,ELEC
9,train_Client_0,11/22/2011,11,1335667.0,0,203,6.0,1,1082,0,0,0,9156,10238,4,ELEC

In [ ]:
print(type(client_0_bills))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 16 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   client_id             1048575 non-null  object
 1   invoice_date          1048575 non-null  object
 2   tarif_type            1048575 non-null  int64
 3   counter_number        1048564 non-null  float64
 4   counter_statue        1048575 non-null  int64
 5   counter_code          1048575 non-null  int64
 6   reading_remarque      1047503 non-null  float64
 7   counter_coefficient   1048575 non-null  int64
 8   consommation_level_1  1048575 non-null  int64
 9   consommation_level_2  1048575 non-null  int64
 10  consommation_level_3  1048575 non-null  int64
 11  consommation_level_4  1048575 non-null  int64
 12  old_index             1048575 non-null  int64
 13  new_index             1048575 non-null  int64
 14  months_number         1048575 non-null  int64
 15  counter_type          1048575 non-null  object
dtypes: float64(2), int64(11), object(3)
memory usage: 128.0+ MB

In [ ]:
df.shape

(1048575, 16)

In [ ]:
rows, columns = df.shape
print(f'Rows: {rows}, Columns: {columns}')

Rows: 1048575, Columns: 16

In [ ]:
categorical_features = df.select_dtypes(include=['object']).columns

In [ ]:
print(f"Number of Categorical_features: {len(categorical_features)}")
print(f"\nCategorical_features: {list(categorical_features)}")

Number of Categorical_features: 3

Categorical_features: ['client_id', 'invoice_date', 'counter_type']

In [ ]:
print(df.isnull().sum())

client_id                0
invoice_date             0
tarif_type               0
counter_number          11
counter_statue           0
counter_code             0
reading_remarque         0
counter_coefficient      0
consommation_level_1     0
consommation_level_2     0
consommation_level_3     0
consommation_level_4     0
old_index                0
new_index                0
months_number            0
counter_type             0
dtype: int64

In [ ]:
df

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,3/24/2014,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,3/29/2013,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,3/23/2015,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,7/13/2015,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,11/17/2016,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,train_Client_128439,6/26/2007,40,42475.0,0,5,6.0,1,106,0,0,0,2249,2355,4,GAZ
1048571,train_Client_128439,10/24/2007,11,464740.0,0,207,6.0,1,476,0,0,0,9385,9861,4,ELEC
1048572,train_Client_128439,5/6/2015,40,42475.0,0,5,8.0,1,63,0,0,0,4927,4990,4,GAZ
1048573,train_Client_128439,5/6/2015,11,464740.0,0,207,9.0,1,459,0,0,0,24265,24724,4,ELEC
1048574,train_Client_128439,10/24/2007,40,42475.0,0,5,6.0,1,43,0,0,0,2355,2398,4,GAZ

In [ ]:
df['reading_remarque'].fillna(df['reading_remarque'].mean(), inplace=True)

<ipython-input-55-8f3815b3c93a>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['reading_remarque'].fillna(df['reading_remarque'].mean(), inplace=True)

In [ ]:
df

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,3/24/2014,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,3/29/2013,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,3/23/2015,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,7/13/2015,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,11/17/2016,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,train_Client_128439,6/26/2007,40,42475.0,0,5,6.0,1,106,0,0,0,2249,2355,4,GAZ
1048571,train_Client_128439,10/24/2007,11,464740.0,0,207,6.0,1,476,0,0,0,9385,9861,4,ELEC
1048572,train_Client_128439,5/6/2015,40,42475.0,0,5,8.0,1,63,0,0,0,4927,4990,4,GAZ
1048573,train_Client_128439,5/6/2015,11,464740.0,0,207,9.0,1,459,0,0,0,24265,24724,4,ELEC
1048574,train_Client_128439,10/24/2007,40,42475.0,0,5,6.0,1,43,0,0,0,2355,2398,4,GAZ

In [ ]:
numeric_features = df.describe()
print(numeric_features)

         tarif_type  counter_number  counter_statue  counter_code  \
count  1.048575e+06    1.048564e+06    1.048575e+06  1.048575e+06
mean   2.013626e+01    1.209212e+11    4.203419e-02  1.722212e+02
std    1.348246e+01    1.646711e+12    3.745414e-01  1.335823e+02
min    8.000000e+00    0.000000e+00    0.000000e+00  5.000000e+00
25%    1.100000e+01    1.214730e+05    0.000000e+00  5.000000e+00
50%    1.100000e+01    4.904750e+05    0.000000e+00  2.030000e+02
75%    4.000000e+01    1.112725e+06    0.000000e+00  2.070000e+02
max    4.500000e+01    2.738110e+13    5.000000e+00  6.000000e+02

       reading_remarque  counter_coefficient  consommation_level_1  \
count      1.048575e+06         1.048575e+06          1.048575e+06
mean       7.315289e+00         1.000236e+00          4.097446e+02
std        1.358930e+00         8.306498e-02          5.882746e+02
min        6.000000e+00         0.000000e+00          0.000000e+00
25%        6.000000e+00         1.000000e+00          7.900000e+01
50%        7.315289e+00         1.000000e+00          2.720000e+02
75%        9.000000e+00         1.000000e+00          6.010000e+02
max        9.000000e+00         5.000000e+01          9.888900e+04

       consommation_level_2  consommation_level_3  consommation_level_4  \
count          1.048575e+06          1.048575e+06          1.048575e+06
mean           1.075682e+02          2.041343e+01          5.405997e+01
std            1.169328e+03          1.636440e+02          9.792183e+02
min            0.000000e+00          0.000000e+00          0.000000e+00
25%            0.000000e+00          0.000000e+00          0.000000e+00
50%            0.000000e+00          0.000000e+00          0.000000e+00
75%            0.000000e+00          0.000000e+00          0.000000e+00
max            8.198860e+05          4.536000e+04          3.435680e+05

          old_index     new_index  months_number
count  1.048575e+06  1.048575e+06   1.048575e+06
mean   1.780314e+04  1.838809e+04   4.632200e+01
std    4.062121e+04  4.122851e+04   2.594754e+03
min    0.000000e+00  0.000000e+00   1.000000e+00
25%    1.792000e+03  2.057000e+03   4.000000e+00
50%    7.718000e+03  8.218000e+03   4.000000e+00
75%    2.181900e+04  2.252000e+04   4.000000e+00
max    2.800280e+06  2.870972e+06   2.944060e+05

In [ ]:
df

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,3/24/2014,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,3/29/2013,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,3/23/2015,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,7/13/2015,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,11/17/2016,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,train_Client_128439,6/26/2007,40,42475.0,0,5,6.0,1,106,0,0,0,2249,2355,4,GAZ
1048571,train_Client_128439,10/24/2007,11,464740.0,0,207,6.0,1,476,0,0,0,9385,9861,4,ELEC
1048572,train_Client_128439,5/6/2015,40,42475.0,0,5,8.0,1,63,0,0,0,4927,4990,4,GAZ
1048573,train_Client_128439,5/6/2015,11,464740.0,0,207,9.0,1,459,0,0,0,24265,24724,4,ELEC
1048574,train_Client_128439,10/24/2007,40,42475.0,0,5,6.0,1,43,0,0,0,2355,2398,4,GAZ

In [ ]:
descriptive_statistics = numeric_features.describe()
descriptive_statistics

,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number
count,8.000000e+00,8.000000e+00,8.000000e+00,8.000000e+00,8.000000e+00,8.000000e+00,8.000000e+00,8.000000e+00,8.000000e+00,8.000000e+00,8.000000e+00,8.000000e+00,8.000000e+00
mean,1.310905e+05,3.643592e+12,1.310726e+05,1.312376e+05,1.310776e+05,1.310786e+05,1.436768e+05,2.337172e+05,1.367649e+05,1.741470e+05,4.923260e+05,5.014948e+05,1.682044e+05
std,3.707197e+05,9.608366e+12,3.707270e+05,3.706603e+05,3.707249e+05,3.707245e+05,3.672573e+05,4.366650e+05,3.687682e+05,3.731970e+05,1.000322e+06,1.023484e+06,3.702990e+05
min,8.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00,1.358930e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
25%,1.100000e+01,3.982245e+05,0.000000e+00,1.014367e+02,6.000000e+00,7.707662e-01,2.237500e+02,0.000000e+00,0.000000e+00,0.000000e+00,6.236500e+03,6.677750e+03,4.000000e+00
50%,1.680936e+01,1.080644e+06,2.101709e-02,1.876106e+02,7.315289e+00,1.000000e+00,4.990096e+02,5.378412e+01,1.020672e+01,2.702999e+01,1.981107e+04,2.045405e+04,2.516100e+01
75%,4.125000e+01,5.023687e+11,1.530906e+00,3.052500e+02,9.000000e+00,1.325018e+01,2.517300e+04,2.058485e+05,1.146273e+04,8.662641e+04,2.926097e+05,2.930651e+05,7.554757e+04
max,1.048575e+06,2.738110e+13,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,2.800280e+06,2.870972e+06,1.048575e+06

In [ ]:
client_0_records = df[df['client_id'] == 'train_Client_0']
client_0_records

,client_id,invoice_date,tarif_type,counter_number,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,3/24/2014,11,1335667.0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,3/29/2013,11,1335667.0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,3/23/2015,11,1335667.0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,7/13/2015,11,1335667.0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,11/17/2016,11,1335667.0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC
5,train_Client_0,7/17/2017,11,1335667.0,207,9.0,1,314,0,0,0,15638,15952,8,ELEC
6,train_Client_0,12/7/2018,11,1335667.0,207,9.0,1,541,0,0,0,15952,16493,12,ELEC
7,train_Client_0,3/19/2019,11,1335667.0,207,9.0,1,585,0,0,0,16493,17078,8,ELEC
8,train_Client_0,7/22/2011,11,1335667.0,203,9.0,1,1200,186,0,0,7770,9156,4,ELEC
9,train_Client_0,11/22/2011,11,1335667.0,203,6.0,1,1082,0,0,0,9156,10238,4,ELEC
10,train_Client_0,11/25/2008,11,1335667.0,203,6.0,1,174,0,0,0,5417,5591,4,ELEC
11,train_Client_0,7/23/2012,11,1335667.0,203,6.0,1,628,0,0,0,10780,11408,4,ELEC
12,train_Client_0,11/29/2012,11,1335667.0,203,6.0,1,886,0,0,0,11408,12294,4,ELEC
13,train_Client_0,7/22/2013,11,1335667.0,203,8.0,1,147,0,0,0,13983,14130,4,ELEC
14,train_Client_0,7/18/2014,11,1335667.0,203,8.0,1,99,0,0,0,14384,14483,4,ELEC
15,train_Client_0,11/24/2014,11,1335667.0,203,8.0,1,141,0,0,0,14483,14624,4,ELEC
16,train_Client_0,11/18/2015,11,1335667.0,207,9.0,1,217,0,0,0,14849,15066,4,ELEC
17,train_Client_0,3/27/2012,11,1335667.0,203,8.0,1,292,0,0,0,10488,10780,4,ELEC
18,train_Client_0,3/30/2011,11,1335667.0,203,6.0,1,497,0,0,0,7273,7770,4,ELEC
19,train_Client_0,2/12/2013,11,1335667.0,203,8.0,1,38,0,0,0,14264,14302,2,ELEC
20,train_Client_0,7/22/2010,11,1335667.0,203,6.0,1,278,0,0,0,6761,7039,4,ELEC
21,train_Client_0,11/24/2010,11,1335667.0,203,6.0,1,234,0,0,0,7039,7273,4,ELEC
22,train_Client_0,10/17/2005,11,1335667.0,203,6.0,1,124,0,0,0,3685,3809,4,ELEC
23,train_Client_0,2/24/2006,11,1335667.0,203,6.0,1,141,0,0,0,3809,3950,4,ELEC
24,train_Client_0,6/23/2006,11,1335667.0,203,6.0,1,162,0,0,0,3950,4112,4,ELEC
25,train_Client_0,10/18/2006,11,1335667.0,203,6.0,1,159,0,0,0,4112,4271,4,ELEC
26,train_Client_0,6/27/2007,11,1335667.0,203,6.0,1,240,0,0,0,4453,4693,4,ELEC
27,train_Client_0,10/25/2007,11,1335667.0,203,6.0,1,276,0,0,0,4693,4969,4,ELEC
28,train_Client_0,2/26/2007,11,1335667.0,203,6.0,1,182,0,0,0,4271,4453,4,ELEC
29,train_Client_0,7/28/2008,11,1335667.0,203,6.0,1,171,0,0,0,5246,5417,4,ELEC
30,train_Client_0,1/4/2009,11,1335667.0,203,6.0,1,315,0,0,0,5591,5906,4,ELEC
31,train_Client_0,7/27/2009,11,1335667.0,203,6.0,1,312,0,0,0,5906,6218,4,ELEC
32,train_Client_0,11/24/2009,11,1335667.0,203,6.0,1,267,0,0,0,6218,6485,4,ELEC
33,train_Client_0,3/29/2010,11,1335667.0,203,6.0,1,276,0,0,0,6485,6761,4,ELEC
34,train_Client_0,1/4/2008,11,1335667.0,203,6.0,1,277,0,0,0,4969,5246,4,ELEC

In [ ]:
label_encoder = LabelEncoder()

In [ ]:
df['counter_type_encoded'] = label_encoder.fit_transform(df['counter_type'])

In [ ]:
print(df)

                   client_id invoice_date  tarif_type  counter_number  \
0             train_Client_0    3/24/2014          11       1335667.0
1             train_Client_0    3/29/2013          11       1335667.0
2             train_Client_0    3/23/2015          11       1335667.0
3             train_Client_0    7/13/2015          11       1335667.0
4             train_Client_0   11/17/2016          11       1335667.0
...                      ...          ...         ...             ...
1048570  train_Client_128439    6/26/2007          40         42475.0
1048571  train_Client_128439   10/24/2007          11        464740.0
1048572  train_Client_128439     5/6/2015          40         42475.0
1048573  train_Client_128439     5/6/2015          11        464740.0
1048574  train_Client_128439   10/24/2007          40         42475.0

         counter_code  reading_remarque  counter_coefficient  \
0                 203               8.0                    1
1                 203               6.0                    1
2                 203               8.0                    1
3                 207               8.0                    1
4                 207               9.0                    1
...               ...               ...                  ...
1048570             5               6.0                    1
1048571           207               6.0                    1
1048572             5               8.0                    1
1048573           207               9.0                    1
1048574             5               6.0                    1

         consommation_level_1  consommation_level_2  consommation_level_3  \
0                          82                     0                     0
1                        1200                   184                     0
2                         123                     0                     0
3                         102                     0                     0
4                         572                     0                     0
...                       ...                   ...                   ...
1048570                   106                     0                     0
1048571                   476                     0                     0
1048572                    63                     0                     0
1048573                   459                     0                     0
1048574                    43                     0                     0

         consommation_level_4  old_index  new_index  months_number  \
0                           0      14302      14384              4
1                           0      12294      13678              4
2                           0      14624      14747              4
3                           0      14747      14849              4
4                           0      15066      15638             12
...                       ...        ...        ...            ...
1048570                     0       2249       2355              4
1048571                     0       9385       9861              4
1048572                     0       4927       4990              4
1048573                     0      24265      24724              4
1048574                     0       2355       2398              4

        counter_type  counter_type_encoded
0               ELEC                     0
1               ELEC                     0
2               ELEC                     0
3               ELEC                     0
4               ELEC                     0
...              ...                   ...
1048570          GAZ                     1
1048571         ELEC                     0
1048572          GAZ                     1
1048573         ELEC                     0
1048574          GAZ                     1

[1048575 rows x 16 columns]

In [ ]:
df.drop(["counter_statue"], axis="columns", inplace=True)

In [ ]:
df.head()

,client_id,invoice_date,tarif_type,counter_number,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,3/24/2014,11,1335667.0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,3/29/2013,11,1335667.0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,3/23/2015,11,1335667.0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,7/13/2015,11,1335667.0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,11/17/2016,11,1335667.0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC